#!/bin/bash -l

#### select resources

#PBS -l place=excl

#PBS -l select=1:ncpus=36

#PBS -l walltime=96:00:00

#### Replace [budget code] below with your project code (e.g. t01)      
#PBS -A sc004

#### change to current working directory
cd /lustre/home/sc004/aa61/HyperSARA_dist_Full/article_sim/

#### load matlab module (setup environment) 
module load matlab/R2018a

rm -rf /tmp/dot_matlab_${PBS_JOBID}*
mkdir /tmp/dot_matlab_${PBS_JOBID}_1
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_1
mkdir /tmp/dot_matlab_${PBS_JOBID}_2
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_2
mkdir /tmp/dot_matlab_${PBS_JOBID}_3
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_3
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_1/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$flag_algo","$gamma1")" > ${flag_algo}_${gamma1}.txt &
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_2/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$flag_algo","$gamma2")" > ${flag_algo}_${gamma2}.txt &
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_3/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$flag_algo","$gamma3")" > ${flag_algo}_${gamma3}.txt &
wait

rm -rf /tmp/dot_matlab_${PBS_JOBID}*



