name: matlab-doc
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - ca-certificates
  - certifi
  - libcxx
  - libffi
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
    - alabaster
    - babel
    - charset-normalizer
    - docutils
    - future
    - idna
    - imagesize
    - importlib-metadata
    - jinja2
    - latexcodec
    - markupsafe
    - miss-hit
    - miss-hit-core
    - packaging
    - pybtex
    - pybtex-docutils
    - pygments
    - pyparsing
    - pytz
    - pyyaml
    - requests
    - six
    - snowballstemmer
    - sphinx
    - sphinx-rtd-theme
    - sphinxcontrib-applehelp
    - sphinxcontrib-bibtex
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-matlabdomain
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - urllib3
    - zipp
