name: matlab-doc
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - appdirs
  - ca-certificates
  - certifi
  - cffi
  - cfgv
  - distlib
  - filelock
  - identify
  - libcxx
  - libffi
  - ncurses
  - nodeenv
  - openssl
  - pip
  - pre-commit
  - pycparser
  - python
  - python_abi
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - toml
  - tzdata
  - ukkonen
  - virtualenv
  - wheel
  - xz
  - yaml
  - zlib
  - pip:
    - alabaster
    - babel
    - charset-normalizer
    - docutils
    - future
    - idna
    - imagesize
    - importlib-metadata
    - jinja2
    - latexcodec
    - markupsafe
    - miss-hit
    - miss-hit-core
    - packaging
    - pybtex
    - pybtex-docutils
    - pygments
    - pyparsing
    - pytz
    - pyyaml
    - requests
    - snowballstemmer
    - sphinx
    - sphinx-rtd-theme
    - sphinxcontrib-applehelp
    - sphinxcontrib-bibtex
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-matlabdomain
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - urllib3
    - zipp
