#!/bin/bash -l

#PBS -N DR_calib

#### select resources
#PBS -l select=1:ncpus=10
#PBS -l walltime=72:00:00
# #PBS -l place=scatter:excl
#### Replace [budget code] below with your project code (e.g. t01)
#PBS -A ec110-guest
#### redirect error & output files

#### load matlab module (setup environment)
module load matlab/R2018a

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

mkdir /lustre/home/sc004/pthouven/Dimensionality-reduced-hyper-SARA-sdwt/pref_${PBS_JOBID}
cp -pr ~/.matlab /lustre/home/sc004/pthouven/Dimensionality-reduced-hyper-SARA-sdwt/pref_${PBS_JOBID}

# mkdir nufft_$PBS_JOBID
#cp -R lib/nufft/* nufft_$PBS_JOBID

export MATLAB_PREFDIR=/lustre/home/sc004/pthouven/Dimensionality-reduced-hyper-SARA-sdwt/pref_$PBS_JOBID

#### execute program
matlab_wrapper -nosplash -nodisplay -nodesktop -r "main_fouRed_simulated_data" > logs/fhs_dr_${PBS_JOBID}.txt

rm -rf /lustre/home/sc004/pthouven/Dimensionality-reduced-hyper-SARA-sdwt/pref_${PBS_JOBID}
# rm -r nufft_$PBS_JOBID
