#!/bin/bash -l

#### select resources

#PBS -l place=excl

#PBS -l select=1:ncpus=36

#PBS -l walltime=30:00:00

#### Replace [budget code] below with your project code (e.g. t01)      
#PBS -A sc004

#### change to current working directory
cd /lustre/home/sc004/aa61/HyperSARA_dist_Full/test3/

#### load matlab module (setup environment) 
module load matlab/R2018a

rm -rf /tmp/dot_matlab_${PBS_JOBID}*
mkdir /tmp/dot_matlab_${PBS_JOBID}_1
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_1
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_1/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$T","$img_size","$tot","$q1","$q2")" > ${T}_${img_size}_${tot}_${q1}_${q2}.txt

rm -rf /tmp/dot_matlab_${PBS_JOBID}*
