#!/bin/bash -l

#### select resources

#PBS -l place=excl

#PBS -l select=1:ncpus=36

#PBS -l walltime=20:00:00

#### Replace [budget code] below with your project code (e.g. t01)      
#PBS -A sc004

#### change to current working directory
cd /lustre/home/sc004/aa61/HyperSARA_dist/hypersara-sdwt2/SPARS/

#### load matlab module (setup environment) 
module load matlab/R2018a

rm -rf /tmp/dot_matlab_${PBS_JOBID}*
mkdir /tmp/dot_matlab_${PBS_JOBID}_1
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_1
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_1/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_test("$flag_algo","$tot","$num_chunk")" > ${flag_algo}_${tot}_${num_chunk}.txt

rm -rf /tmp/dot_matlab_${PBS_JOBID}*



