#!/bin/bash -l

#### select resources

#PBS -l place=excl

#PBS -l select=1:ncpus=36

#PBS -l walltime=10:00:00

#### Replace [budget code] below with your project code (e.g. t01)      
#PBS -A sc004

#### change to current working directory
cd /lustre/home/sc004/aa61/HyperSARA_dist_Full/test2/

#### load matlab module (setup environment) 
module load matlab/R2018a

rm -rf /tmp/dot_matlab_${PBS_JOBID}*
mkdir /tmp/dot_matlab_${PBS_JOBID}_1
mkdir /tmp/dot_matlab_${PBS_JOBID}_2
mkdir /tmp/dot_matlab_${PBS_JOBID}_3
mkdir /tmp/dot_matlab_${PBS_JOBID}_4
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_1
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_2
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_3
cp -pr ~/.matlab /tmp/dot_matlab_${PBS_JOBID}_4
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_1/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$flag_algo","$Qc1")" > ${flag_algo}_${Qc1}.txt &
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_1/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$flag_algo","$Qc2")" > ${flag_algo}_${Qc2}.txt &
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_1/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$flag_algo","$Qc3")" > ${flag_algo}_${Qc3}.txt &
export MATLAB_PREFDIR=/tmp/dot_matlab_${PBS_JOBID}_1/.matlab/R2018a
matlab -nodisplay -nodisplay -nodesktop -r "main_simulated_data_FINAL_clean("$flag_algo","$Qc4")" > ${flag_algo}_${Qc4}.txt &
wait

rm -rf /tmp/dot_matlab_${PBS_JOBID}*
